const lang = {
    en: {
        search: "Search",
        searchPlaceholder: "What would you like to watch...",
        nowPlayingText: "Now playing",
        latestText: "Latest",
        trendingText: "Trending",
        popularText: "Popular",
        upcomingText: "Upcoming",
        awardWiningText: "Award wining",
        signInText: "Sign In",
        signOutText: "Sign Out",
        gptSearchText: "GPT Search",
        gptReturnText: "Home",
    },
    hindi: {
        search: "खोज",
        searchPlaceholder: "आप क्या देखना चाहेंगे...",
        nowPlayingText: "नाउ प्लेइंग",
        trendingText: "ट्रेंडिंग",
        popularText: "पॉपुलर",
        upcomingText: "अपकमिंग",
        awardWiningText: "अवार्ड विनिंग",
        // signInText: "साइन इन",
        signInText: "Sign In",
        signOutText: "साइन आउट",
        gptSearchText: "जीपीटी सर्च",
        gptReturnText: "होम",
    },
    assamese: {
        search: "সন্ধান",
        searchPlaceholder: "আপুনি কি চাব বিচাৰে...",
        nowPlayingText: "নাও প্লেয়িং",
        trendingText: "ট্ৰেণ্ডিং",
        popularText: "জনপ্ৰিয়",
        upcomingText: "আগন্তুক",
        awardWiningText: "বঁটা বিজয়ী",
        // signInText: "চাইন ইন",
        signInText: "Sign In",
        signOutText: "চাইন আউট",
        gptSearchText: "জিপিটি চাৰ্চ",
        gptReturnText: "হোম",
    },
    punjabi: {
        search: "ਖੋਜ",
        searchPlaceholder: "ਤੁਸੀਂ ਕੀ ਦੇਖਣਾ ਚਾਹੋਗੇ...",
        nowPlayingText: "ਹੁਣ ਡਿਸਪਲੇਅ",
        trendingText: "ਰੁਝਾਨ",
        popularText: "ਪ੍ਰਸਿੱਧ",
        upcomingText: "ਆਉਣ",
        awardWiningText: "ਅਵਾਰਡ",
        signInText: "Sign In",
        signOutText: "ਸਾਇਨ ਆਉਟ",
        gptSearchText: "ਜੀਪੀਟੀ ਖੋਜ",
        gptReturnText: "ਹੋਮ",
    },
    marathi: {
        search: "शोधा",
        searchPlaceholder: "तुम्हाला काय पहायला आवडेल...",
        nowPlayingText: "आता प्रदर्शित",
        trendingText: "ट्रेंडिंग",
        popularText: "लोकप्रिय",
        upcomingText: "आगामी",
        awardWiningText: "पुरस्कार विनिंग",
        signInText: "Sign In",
        signOutText: "साइन आउट",
        gptSearchText: "जीपीटी शोध",
        gptReturnText: "होम",
    },
    gujarati: {
        search: "શોધો",
        searchPlaceholder: "તમે શું જોવા માંગો છો...",
        nowPlayingText: "હવે પ્રદર્શન",
        trendingText: "ટ્રેન્ડિંગ",
        popularText: "લોકપ્રિય",
        upcomingText: "પાછા ફરવું",
        awardWiningText: "એવોર્ડ વાઇનિંગ",
        signInText: "Sign In",
        signOutText: "સાઇન આઉટ",
        gptSearchText: "જીપીટી શોધ",
        gptReturnText: "હોમ",
    },
    french: {
        search: "Recherche",
        searchPlaceholder: "Que souhaiteriez-vous regarder...",
        nowPlayingText: "Je joue en ce moment",
        trendingText: "Tendance",
        popularText: "Populaire",
        upcomingText: "Prochaine",
        awardWiningText: "Primé",
        // signInText: "Se connecter",
        signInText: "Sign In",
        signOutText: "Se déconnecter",
        gptSearchText: "Recherche GPT",
        gptReturnText: "Maison",
    },
};

export default lang;


export const NOTIFICATIONS = [
    "Reminder: For a smoother experience on Cinestream, we recommend using the Brave browser , It blocks ads and auto-redirects, making your streaming faster, easier & safer.",
    "* New movies added to CineStream",
    "* Coming Soon: Trailer - Series - Movies World's Trending News",
  ];

